#!/usr/bin/env bash

sudo xbpa-install libXcomposit-devel libXdamage-devel libdrm-devel asciidoc MesaLib-devel

now=`pwd`
git clone https://github.com/tryone144/compton.git ~/Github

cd ~/Github/compton 
make
make docs
make install

cd $now
