#!/bin/bash/
set -e

now=$PWD

mkdir ~/suckless
cd ~/suckless
git clone https://github.com/dopeduck/dwm
git clone https://github.com/dopeduck/slstatus
git clone https://git.suckless.org/slock


sudo xbps-install -Sy libXrandr-devel \
    libX11-devel \
    libXft-devel \
    libXinerama-devel \
    base-devel

cd dwm
sudo make clean install

cd ../slock
sudo make clean install

cd ../slstatus
sudo make clean install

cd $now
