#!/bin/bash/
set -e

sudo xbps-install -y ImageMagick \
    acpi \
    base-devel \
    broadcom-bt-firmware \
    clang \
    compton \
    ctags \
    curl \
    dmenu \
    feh \
    ffmpeg \
    ffmpegthumbnailer \
    firefox \
    fzf \
    git \
    htop \
    libX11-devel \
    libXft-devel \
    mpc \
    mpv \
    neofetch \
    neovim \
    noto-fonts-emoji \
    picard \
    python-pip \
    qutebrowser \
    ranger \
    redshift \
    scrot \
    tree \
    unclutter \
    unzip \
    w3m \
    w3m-img \
    wget \
    zathura \
    rxvt-unicode \
    zathura-pdf-mupdf

pip3 install neovim --user
