#!/bin/bash
set -e

sudo xbps-install -S `cat pkg`

sudo rm -rf /var/service/agetty-tty4
sudo rm -rf /var/service/agetty-tty5
sudo rm -rf /var/service/agetty-tty6
sudo rm -rf /var/service/dhcpcd

sudo ln -sf /etc/sv/NetworkManager/ /var/service
sudo ln -sf /etc/sv/dbus/ /var/service
sudo ln -sf /etc/sv/acpid /var/service
sudo ln -sf /etc/sv/bluetoothd /var/service
sudo ln -sf /etc/sv/ufw /var/service
sudo ln -sf /etc/sv/polkitd /var/service
sudo ln -sf /etc/sv/elogind /var/service

sudo xbps-reconfigure ufw
sudo ufw enable

sudo cp net/50-org.freedesktop.NetworkManager.rules /etc/polkit-1/rules.d/

sudo cp bluetooth/51-blueman.rules /etc/polkit-1/rules.d/

sudo gpasswd -a prat bluetooth
sudo gpasswd -a prat network

if [[ -f /etc/X11/xorg.conf.d/ ]]; then
  sudo cp touchpad/40-libinput.conf /etc/X11/xorg.conf.d/
else
  sudo mkdir /etc/X11/xorg.conf.d/
  sudo cp touchpad/40-libinput.conf /etc/X11/xorg.conf.d/
fi

curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)
