#!/bin/bash
set -e

sudo xbps-install -S `cat pkg-i`

sudo rm -rf /var/service/agetty-tty4
sudo rm -rf /var/service/agetty-tty5
sudo rm -rf /var/service/agetty-tty6
sudo rm -rf /var/service/dhcpcd

sudo gpasswd -a prat bluetooth
sudo gpasswd -a prat network
sudo ln -sf /etc/sv/NetworkManager/ /var/service
sudo ln -sf /etc/sv/dbus/ /var/service
sudo ln -sf /etc/sv/acpid /var/service
sudo ln -sf /etc/sv/bluetoothd /var/service
sudo ln -sf /etc/sv/ufw /var/service

sudo xbps-reconfigure ufw
sudo ufw enable

sudo cp net/50-org.freedesktop.NetworkManager.rules /etc/polkit-1/rules.d/50-org.freedesktop.NetworkManager.rules

sudo cp bluetooth/51-blueman.rules /etc/polkit-1/rules.d/

if [[ -f /etc/X11/xorg.conf.d/ ]]; then
  sudo cp touchpad/40-libinput.conf /etc/X11/xorg.conf.d/
else
  sudo mkdir /etc/X11/xorg.conf.d/
  sudo cp touchpad/40-libinput.conf /etc/X11/xorg.conf.d/
fi
