#!/usr/bin/env bash

sudo xbps-install -S libX11-devel libXft-devel libXinerama-devel libXrandr-devel

now=`pwd`
git clone https://github.com/pratSurek/.dwm ~/

cd ~/.dwm
sudo make clean install

cd $now

git clone https://github.com/pratSurek/.st ~/
cd ~/.st
sudo make clean install

cd $now
